spring:
  cloud:
    gateway:
      routes:
        - id: Springboot-service-discovery-client
          uri: http://localhost:4040/
          Predicates:
            - Path=/service1/**
        - id: Springboot-service-discovery-client-2
          uri: http://localhost:5050/
          Predicates:
            - Path=/service2/**